# Project Name
TARGET = cloudyreverb

# Sources
CPP_SOURCES = cloudyreverb.cpp
# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

C_INCLUDES += \
-I../../eurorack \

# Include terrarium.h
C_INCLUDES += -I../../Terrarium




